language: node_js
matrix:
  include:
    - node_js: "6"
      script: npm run test-ci
    - node_js: "4"
      script: npm test
os:
  - linux
  # Currently, osx takes too long time to run tests on travis
  # - osx
sudo: false
cache:
  directories:
    - node_modules
notifications:
  email: false
